P3331R0追加
onihusube/blog pull request #40
Opened 2024-12-19 12:30 UTC by Sakky4869

「P3331 R0 Accessing The First and Last Elements in Associative Containers」の要約になります。

https://github.com/onihusube/blog/issues/39#issuecomment-2535909825

2024-12-19 16:50 UTC, onihusube requested changes
ありがとうございます！
2点ほど気になったので修正をお願いします。

1. 表中も含めて、コード片は バッククオートでくくるようにしてください
2. ラストにhttps://github.com/cplusplus/papers/issues/ のissueトラッカーへのリンクを貼っておいて下さい
    - 張り方は既存記事参照

2024-12-25 00:28 UTC, Sakky4869 commented
ご指摘いただいた内容を反映しました！
ご確認お願い致します！

2024-12-27 15:12 UTC, onihusube approved these changes

2024-12-27 15:13 UTC, merged

2024-12-27 15:14 UTC, onihusube commented
ありがとうございます！
クレジットはあとで私の方で入れますが、その際表示したいアカウントもしくはサイト等ありましたらお知らせください（デフォルトはgithubのアカウントへリンクします）

2024-12-28 06:20 UTC, Sakky4869 commented
ありがとうございます！
GitHubアカウントで問題ございません
クレジットは想像してなかったのでビックリしてます！